version: '3'

services:

  mysql:
    build: .docker/mysql
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  postgres:
    build: .docker/postgres
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
